name: Restore Telegram Webhook

on:
  deployment_status:
    types: [success]
  workflow_dispatch: # Allow manual trigger

jobs:
  restore-webhook:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Restore Telegram Webhook
        run: |
          echo "🔧 Restoring Telegram webhook after deployment..."
          
          # Wait a moment for deployment to be fully ready
          sleep 10
          
          # Set the webhook
          response=$(curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/setWebhook" \
            -H "Content-Type: application/json" \
            -d '{"url": "https://hyphn-pa.vercel.app/api"}')
          
          echo "📡 Webhook response: $response"
          
          # Verify webhook is set
          verification=$(curl -s "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/getWebhookInfo")
          echo "✅ Webhook verification: $verification"
          
          echo "🎉 Webhook restoration complete!"

      - name: Test Endpoint
        run: |
          echo "🧪 Testing Vercel endpoint..."
          response=$(curl -s "https://hyphn-pa.vercel.app/api")
          echo "📊 Endpoint response: $response"
